version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u171-jdk
    working_directory: ~/repo
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/jagrosh/MusicBot/compare/61d4c51276a77b83b93fd8b4b9f4ec3570d45a0d...f1e301b48e8a0d79ed9d24ecfae7335a5bbb8dcd
    - MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn integration-test
    - run: mvn package
    - store_artifacts:
        paths: /tmp/artifacts
workflows:
  version: 2
  workflow:
    jobs:
    - build
